export const idolProfiles = {
	장원영: {
		englishName: "JANG WONYOUNG",
		birth: "2004",
		hometown: "서울 서초구",
		hobby: "필라테스",
		mbti: "ISFP",
		group: "IVE",
		agency: "STARSHIP",
		groupLogo: "/images/STARSHIP.png",
		instagram: "https://www.instagram.com/ivestarship/",
		fancam: "https://www.youtube.com/watch?v=4BeckMw9vao",
	},
	안유진: {
		englishName: "AN YUJIN",
		birth: "2003",
		hometown: "대전",
		hobby: "사진 찍기",
		mbti: "ENFP",
		group: "IVE",
		agency: "STARSHIP",
		groupLogo: "/images/STARSHIP.png",
		instagram: "https://www.instagram.com/ivestarship/",
		fancam: "https://www.youtube.com/watch?v=Vk4urpcsntk",
	},
	리즈: {
		englishName: "Liz",
		birth: "2007",
		hometown: "경기도",
		hobby: "음악 감상",
		mbti: "ISFP",
		group: "IVE",
		agency: "STARSHIP",
		groupLogo: "/images/STARSHIP.png",
		instagram: "https://www.instagram.com/ivestarship/",
		fancam: "https://www.youtube.com/watch?v=h7OmJZS7sxY",
	},
	레이: {
		englishName: "REI",
		birth: "2004",
		hometown: "일본",
		hobby: "독서",
		mbti: "INFJ",
		group: "IVE",
		agency: "STARSHIP",
		groupLogo: "/images/STARSHIP.png",
		instagram: "https://www.instagram.com/ivestarship/",
		fancam: "https://www.youtube.com/watch?v=mKLLdYSl3Lk",
	},
	이서: {
		englishName: "LEESEO",
		birth: "2007",
		hometown: "경북 대구",
		hobby: "그림 그리기",
		mbti: "ENFP",
		group: "IVE",
		agency: "STARSHIP",
		groupLogo: "/images/STARSHIP.png",
		instagram: "https://www.instagram.com/ivestarship/",
		fancam: "https://www.youtube.com/watch?v=NOVaFSRBZrk",
	},
	가을: {
		englishName: "GAEUL",
		birth: "2002",
		hometown: "인천",
		hobby: "영화 감상",
		mbti: "ISTJ",
		group: "IVE",
		agency: "STARSHIP",
		groupLogo: "/images/STARSHIP.png",
		instagram: "https://www.instagram.com/ivestarship/",
		fancam: "https://www.youtube.com/watch?v=rjspo0mId2s",
	},
	하니: {
		englishName: "HANNI",
		birth: "2004",
		hometown: "호치민",
		hobby: "캘리그래피",
		mbti: "INFP",
		group: "NewJeans",
		agency: "ADOR",
		groupLogo: "/images/ADOR.png",
		instagram: "https://www.instagram.com/newjeans_official/",
		fancam: "https://www.youtube.com/watch?v=lmJPeFW75qQ",
	},
	해린: {
		englishName: "HAERIN",
		birth: "2006",
		hometown: "김해",
		hobby: "고양이 영상 보기",
		mbti: "ISTP",
		group: "NewJeans",
		agency: "ADOR",
		groupLogo: "/images/ADOR.png",
		instagram: "https://www.instagram.com/newjeans_official/",
		fancam: "https://www.youtube.com/watch?v=k3jV6DMTCSE",
	},
	민지: {
		englishName: "MINJI",
		birth: "2004",
		hometown: "강릉",
		hobby: "산책",
		mbti: "ESTJ",
		group: "NewJeans",
		agency: "ADOR",
		groupLogo: "/images/ADOR.png",
		instagram: "https://www.instagram.com/newjeans_official/",
		fancam: "https://www.youtube.com/watch?v=p1cE9T0CFCQ",
	},
	혜인: {
		englishName: "HYEIN",
		birth: "2008",
		hometown: "인천",
		hobby: "사진 수집",
		mbti: "ENFP",
		group: "NewJeans",
		agency: "ADOR",
		groupLogo: "/images/ADOR.png",
		instagram: "https://www.instagram.com/newjeans_official/",
		fancam: "https://www.youtube.com/watch?v=Wz_mVys9Z4w",
	},
	다니엘: {
		englishName: "DANIELLE",
		birth: "2005",
		hometown: "뉴캐슬",
		hobby: "요리",
		mbti: "ENFP",
		group: "NewJeans",
		agency: "ADOR",
		groupLogo: "/images/ADOR.png",
		instagram: "https://www.instagram.com/newjeans_official/",
		fancam: "https://www.youtube.com/watch?v=D0x7KSdVWYs",
	},
	카리나: {
		englishName: "KARINA",
		birth: "2000",
		hometown: "수원",
		hobby: "댄스",
		mbti: "ENFP",
		group: "AESPA",
		agency: "SM",
		groupLogo: "/images/SM.png",
		instagram: "https://www.instagram.com/aespa_official/",
		fancam: "https://www.youtube.com/watch?v=pgP3l3VfTJE",
	},
	윈터: {
		englishName: "WINTER",
		birth: "2001",
		hometown: "양산",
		hobby: "게임",
		mbti: "INFJ",
		group: "AESPA",
		agency: "SM",
		groupLogo: "/images/SM.png",
		instagram: "https://www.instagram.com/aespa_official/",
		fancam: "https://www.youtube.com/watch?v=UAQT5Hgrm1Q",
	},
	닝닝: {
		englishName: "NINGNING",
		birth: "2002",
		hometown: "중국 하얼빈",
		hobby: "노래 부르기",
		mbti: "ISFP",
		group: "AESPA",
		agency: "SM",
		groupLogo: "/images/SM.png",
		instagram: "https://www.instagram.com/aespa_official/",
		fancam: "https://www.youtube.com/watch?v=NRvqGh6nGWA",
	},
	지젤: {
		englishName: "GISELLE",
		birth: "2000",
		hometown: "일본 도쿄",
		hobby: "랩 작사",
		mbti: "ENFP",
		group: "AESPA",
		agency: "SM",
		groupLogo: "/images/SM.png",
		instagram: "https://www.instagram.com/aespa_official/",
		fancam: "https://www.youtube.com/watch?v=xWyeg5qYL2I",
	},
	카즈하: {
		englishName: "KAZUHA",
		birth: "2003",
		hometown: "일본",
		hobby: "발레",
		mbti: "ISFP",
		group: "LE SSERAFIM",
		agency: "SOURCE MUSIC",
		groupLogo: "/images/SOURCEmusic.png",
		instagram: "https://www.instagram.com/le_sserafim/",
		fancam: "https://www.youtube.com/watch?v=tRU_QbQCYn0",
	},
	김채원: {
		englishName: "KIM CHAEWON",
		birth: "2000",
		hometown: "서울",
		hobby: "요가",
		mbti: "ISTP",
		group: "LE SSERAFIM",
		agency: "SOURCE MUSIC",
		groupLogo: "/images/SOURCEmusic.png",
		instagram: "https://www.instagram.com/le_sserafim/",
		fancam: "https://www.youtube.com/watch?v=_w60TKkK62I",
	},
	사쿠라: {
		englishName: "SAKURA",
		birth: "1998",
		hometown: "일본 가고시마",
		hobby: "게임 방송 보기",
		mbti: "INFP",
		group: "LE SSERAFIM",
		agency: "SOURCE MUSIC",
		groupLogo: "/images/SOURCEmusic.png",
		instagram: "https://www.instagram.com/le_sserafim/",
		fancam: "https://www.youtube.com/watch?v=PDNpCOAEKOA",
	},
	홍은채: {
		englishName: "HONG EUNCHAE",
		birth: "2006",
		hometown: "광주",
		hobby: "요리",
		mbti: "ENFP",
		group: "LE SSERAFIM",
		agency: "SOURCE MUSIC",
		groupLogo: "/images/SOURCEmusic.png",
		instagram: "https://www.instagram.com/le_sserafim/",
		fancam: "https://www.youtube.com/watch?v=ySg9EIhiMgE",
	},
	허윤진: {
		englishName: "HUH YUNJIN",
		birth: "2001",
		hometown: "미국",
		hobby: "기타 연주",
		mbti: "ENFP",
		group: "LE SSERAFIM",
		agency: "SOURCE MUSIC",
		groupLogo: "/images/SOURCEmusic.png",
		instagram: "https://www.instagram.com/le_sserafim/",
		fancam: "https://www.youtube.com/watch?v=eSKN_H2D25M",
	},
	설윤: {
		englishName: "SULLYOON",
		birth: "2004",
		hometown: "대구",
		hobby: "패션 스타일링",
		mbti: "INFJ",
		group: "NMIXX",
		agency: "JYP",
		groupLogo: "/images/JYP.png",
		instagram: "https://www.instagram.com/nmixx_official/",
		fancam: "https://www.youtube.com/watch?v=q0F0hrpHxdo",
	},
	해원: {
		englishName: "HAEWON",
		birth: "2003",
		hometown: "인천",
		hobby: "노래 연습",
		mbti: "ISFJ",
		group: "NMIXX",
		agency: "JYP",
		groupLogo: "/images/JYP.png",
		instagram: "https://www.instagram.com/nmixx_official/",
		fancam: "https://www.youtube.com/watch?v=eyhjqIxgvug",
	},
	지우: {
		englishName: "JIWOO",
		birth: "2005",
		hometown: "서울",
		hobby: "춤 연습",
		mbti: "ENTP",
		group: "NMIXX",
		agency: "JYP",
		groupLogo: "/images/JYP.png",
		instagram: "https://www.instagram.com/nmixx_official/",
		fancam: "https://www.youtube.com/watch?v=S9800GcCTco",
	},
	베이: {
		englishName: "BAE",
		birth: "2004",
		hometown: "양산",
		hobby: "그림 그리기",
		mbti: "ESFP",
		group: "NMIXX",
		agency: "JYP",
		groupLogo: "/images/JYP.png",
		instagram: "https://www.instagram.com/nmixx_official/",
		fancam: "https://www.youtube.com/watch?v=v1iPeohKoKg",
	},
	규진: {
		englishName: "KYUJIN",
		birth: "2006",
		hometown: "성남",
		hobby: "운동",
		mbti: "ESTJ",
		group: "NMIXX",
		agency: "JYP",
		groupLogo: "/images/JYP.png",
		instagram: "https://www.instagram.com/nmixx_official/",
		fancam: "https://www.youtube.com/live/qAkFm4PZYYs",
	},
	릴리: {
		englishName: "LILY",
		birth: "2002",
		hometown: "호주",
		hobby: "기타 연주",
		mbti: "ENFP",
		group: "NMIXX",
		agency: "JYP",
		groupLogo: "/images/JYP.png",
		instagram: "https://www.instagram.com/nmixx_official/",
		fancam: "https://www.youtube.com/watch?v=2hsNDr0QWNg",
	},
	지수: {
		englishName: "JISOO",
		birth: "1995",
		hometown: "서울",
		hobby: "그림 그리기",
		mbti: "INFJ",
		group: "BLACKPINK",
		agency: "YG",
		groupLogo: "/images/YG.png",
		instagram: "https://www.instagram.com/blackpinkofficial/",
		fancam: "https://www.youtube.com/watch?v=67aBenO-MeU",
	},
	제니: {
		englishName: "JENNIE",
		birth: "1996",
		hometown: "서울",
		hobby: "패션 디자인",
		mbti: "INFP",
		group: "BLACKPINK",
		agency: "YG",
		groupLogo: "/images/YG.png",
		instagram: "https://www.instagram.com/blackpinkofficial/",
		fancam: "https://www.youtube.com/watch?v=3ipaG-bWI7s",
	},
	로제: {
		englishName: "ROSÉ",
		birth: "1997",
		hometown: "뉴질랜드",
		hobby: "기타 연주",
		mbti: "ENFP",
		group: "BLACKPINK",
		agency: "YG",
		groupLogo: "/images/YG.png",
		instagram: "https://www.instagram.com/blackpinkofficial/",
		fancam: "https://www.youtube.com/watch?feature=shared&v=m1wtAs4cyT4",
	},
	리사: {
		englishName: "LISA",
		birth: "1997",
		hometown: "태국",
		hobby: "춤",
		mbti: "ISFP",
		group: "BLACKPINK",
		agency: "YG",
		groupLogo: "/images/YG.png",
		instagram: "https://www.instagram.com/blackpinkofficial/",
		fancam: "https://www.youtube.com/watch?v=9bHDfHP3Rb8",
	},
	원빈: {
		englishName: "WONBIN",
		birth: "2002",
		hometown: "울산",
		hobby: "기타 연주",
		mbti: "INFP",
		group: "RIIZE",
		agency: "SM",
		groupLogo: "/images/SM.png",
		instagram: "https://www.instagram.com/riize_official/",
		fancam: "https://www.youtube.com/watch?v=6UnE-maug2k",
	},
	앤톤: {
		englishName: "ANTON",
		birth: "2004",
		hometown: "미국",
		hobby: "작곡",
		mbti: "ISFP",
		group: "RIIZE",
		agency: "SM",
		groupLogo: "/images/SM.png",
		instagram: "https://www.instagram.com/riize_official/",
		fancam: "https://www.youtube.com/watch?v=QiRNwY_OO6Q",
	},
	차은우: {
		englishName: "CHA EUNWOO",
		birth: "1997",
		hometown: "경기",
		hobby: "사진 찍기",
		mbti: "INFJ",
		group: "ASTRO",
		agency: "FANTAGIO",
		groupLogo: "/images/FANTAGIO.png",
		instagram: "https://www.instagram.com/officialastro/",
		fancam: "https://www.youtube.com/watch?v=xiodq-7seYA",
	},
	문빈: {
		englishName: "MOON BIN",
		birth: "1998",
		hometown: "청주",
		hobby: "운동",
		mbti: "ISFP",
		group: "ASTRO",
		agency: "FANTAGIO",
		groupLogo: "/images/FANTAGIO.png",
		instagram: "https://www.instagram.com/officialastro/",
		fancam: "https://www.youtube.com/watch?v=TL2xzJprAZo",
	},
	라키: {
		englishName: "ROCKY",
		birth: "1999",
		hometown: "진주",
		hobby: "안무 창작",
		mbti: "ENFP",
		group: "ASTRO",
		agency: "FANTAGIO",
		groupLogo: "/images/FANTAGIO.png",
		instagram: "https://www.instagram.com/officialastro/",
		fancam: "https://www.youtube.com/watch?v=xZv39_JqE6g",
	},
	윤산하: {
		englishName: "YOON SANHA",
		birth: "2000",
		hometown: "서울",
		hobby: "게임",
		mbti: "INFP",
		group: "ASTRO",
		agency: "FANTAGIO",
		groupLogo: "/images/FANTAGIO.png",
		instagram: "https://www.instagram.com/officialastro/",
		fancam: "https://www.youtube.com/watch?v=qloR_k6ZI_U",
	},
	키: {
		englishName: "KEY",
		birth: "1991",
		hometown: "대구",
		hobby: "패션 스타일링",
		mbti: "ENTJ",
		group: "SHINee",
		agency: "SM",
		groupLogo: "/images/SM.png",
		instagram: "https://www.instagram.com/shinee/",
		fancam: "https://www.youtube.com/watch?v=l_kMRwCe9h0",
	},
	민호: {
		englishName: "MINHO",
		birth: "1991",
		hometown: "인천",
		hobby: "농구",
		mbti: "ESTP",
		group: "SHINee",
		agency: "SM",
		groupLogo: "/images/SM.png",
		instagram: "https://www.instagram.com/shinee/",
		fancam: "https://www.youtube.com/watch?v=Az6yUzFDz1U",
	},
	태민: {
		englishName: "TAEMIN",
		birth: "1993",
		hometown: "서울",
		hobby: "그림 그리기",
		mbti: "INFP",
		group: "SHINee",
		agency: "SM",
		groupLogo: "/images/SM.png",
		instagram: "https://www.instagram.com/shinee/",
		fancam: "https://www.youtube.com/watch?v=K2oByTvJ6lk",
	},
	종현: {
		englishName: "JONGHYUN",
		birth: "1990",
		hometown: "서울",
		hobby: "작사",
		mbti: "ISFP",
		group: "SHINee",
		agency: "SM",
		groupLogo: "/images/SM.png",
		instagram: "https://www.instagram.com/shinee/",
		fancam: "https://www.youtube.com/watch?v=btEdyStLjRQ",
	},
	온유: {
		englishName: "ONEW",
		birth: "1989",
		hometown: "경기",
		hobby: "요리",
		mbti: "ISFJ",
		group: "SHINee",
		agency: "SM",
		groupLogo: "/images/SM.png",
		instagram: "https://www.instagram.com/shinee/",
		fancam: "https://www.youtube.com/watch?v=3yFiW-HupY4",
	},
	재현: {
		englishName: "JAEHYUN",
		birth: "1997",
		hometown: "서울",
		hobby: "피아노 연주",
		mbti: "INFJ",
		group: "NCT",
		agency: "SM",
		groupLogo: "/images/SM.png",
		instagram: "https://www.instagram.com/nct/",
		fancam: "https://www.youtube.com/watch?v=szvw-WOg3aU",
	},
	도영: {
		englishName: "DOYOUNG",
		birth: "1996",
		hometown: "서울",
		hobby: "독서",
		mbti: "ISFJ",
		group: "NCT",
		agency: "SM",
		groupLogo: "/images/SM.png",
		instagram: "https://www.instagram.com/nct/",
		fancam: "https://www.youtube.com/watch?v=RwJ2TBB43lM",
	},
	태용: {
		englishName: "TAEYONG",
		birth: "1995",
		hometown: "서울",
		hobby: "춤추기",
		mbti: "ENFP",
		group: "NCT",
		agency: "SM",
		groupLogo: "/images/SM.png",
		instagram: "https://www.instagram.com/nct/",
		fancam: "https://www.youtube.com/watch?v=sECXv8Mbjbg",
	},
	신유: {
		englishName: "SHIN YU",
		birth: "2004",
		hometown: "서울",
		hobby: "운동",
		mbti: "ENFP",
		group: "TWS",
		agency: "PLEDIS",
		groupLogo: "/images/PLEDIS.png",
		instagram: "https://www.instagram.com/tws.official/",
		fancam: "https://www.youtube.com/watch?v=BtFPgl0tC0k",
	},
	한진: {
		englishName: "HANJIN",
		birth: "2004",
		hometown: "경기",
		hobby: "영화 감상",
		mbti: "ISTP",
		group: "TWS",
		agency: "PLEDIS",
		groupLogo: "/images/PLEDIS.png",
		instagram: "https://www.instagram.com/tws.official/",
		fancam: "https://www.youtube.com/watch?v=X-DLqSIv3YA",
	},
	경민: {
		englishName: "KYUNGMIN",
		birth: "2005",
		hometown: "인천",
		hobby: "독서",
		mbti: "INFP",
		group: "TWS",
		agency: "PLEDIS",
		groupLogo: "/images/PLEDIS.png",
		instagram: "https://www.instagram.com/tws.official/",
		fancam: "https://www.youtube.com/watch?v=YHPGeGm32O4",
	},
	지훈: {
		englishName: "JIHOON",
		birth: "2004",
		hometown: "대전",
		hobby: "게임",
		mbti: "ISFP",
		group: "TWS",
		agency: "PLEDIS",
		groupLogo: "/images/PLEDIS.png",
		instagram: "https://www.instagram.com/tws.official/",
		fancam: "https://www.youtube.com/watch?v=BzSV1_K-P7A",
	},
	연준: {
		englishName: "YEONJUN",
		birth: "1999",
		hometown: "서울",
		hobby: "패션 코디",
		mbti: "ENTP",
		group: "TXT",
		agency: "HYBE",
		groupLogo: "/images/HYBE.png",
		instagram: " https://www.instagram.com/txt_bighit/",
		fancam: "https://www.youtube.com/watch?v=sx4hPjppi6E",
	},
	범규: {
		englishName: "BEOMGYU",
		birth: "2001",
		hometown: "대구",
		hobby: "기타 치기",
		mbti: "INFP",
		group: "TXT",
		agency: "HYBE",
		groupLogo: "/images/HYBE.png",
		instagram: " https://www.instagram.com/txt_bighit/",
		fancam: "https://www.youtube.com/watch?v=rDnPaRFDnUk",
	},
	수빈: {
		englishName: "SOOBIN",
		birth: "2000",
		hometown: "서울",
		hobby: "동물 돌보기",
		mbti: "ISFJ",
		group: "TXT",
		agency: "HYBE",
		groupLogo: "/images/HYBE.png",
		instagram: " https://www.instagram.com/txt_bighit/",
		fancam: "https://www.youtube.com/watch?v=ibnQ1bH8fIM",
	},
	진: {
		englishName: "JIN",
		birth: "1992",
		hometown: "과천",
		hobby: "요리",
		mbti: "INFP",
		group: "BTS",
		agency: "HYBE",
		groupLogo: "/images/HYBE.png",
		instagram: "https://www.instagram.com/bts.bighitofficial/",
		fancam: "https://www.youtube.com/watch?v=MilKNyALZ6w",
	},
	정국: {
		englishName: "JUNGKOOK",
		birth: "1997",
		hometown: "부산",
		hobby: "복싱",
		mbti: "ISFP",
		group: "BTS",
		agency: "HYBE",
		groupLogo: "/images/HYBE.png",
		instagram: "https://www.instagram.com/bts.bighitofficial/",
		fancam: "https://www.youtube.com/watch?v=w5XxXWJrARU",
	},
	뷔: {
		englishName: "V",
		birth: "1995",
		hometown: "대구",
		hobby: "사진 찍기",
		mbti: "ENFP",
		group: "BTS",
		agency: "HYBE",
		groupLogo: "/images/HYBE.png",
		instagram: "https://www.instagram.com/bts.bighitofficial/",
		fancam: "https://www.youtube.com/watch?v=AX0CIHA2f1M",
	},
	유진: {
		englishName: "YUJIN",
		birth: "2001",
		hometown: "서울",
		hobby: "운동",
		mbti: "ENFP",
		group: "ZEROBASEONE",
		agency: "WAKEONE",
		groupLogo: "/images/WAKEONE.png",
		instagram: "https://www.instagram.com/zb1_official/",
		fancam: "https://www.youtube.com/watch?v=T0h0r3q_9UA",
	},
	요시: {
		englishName: "YOSHI",
		birth: "2000",
		hometown: "일본",
		hobby: "그림 그리기",
		mbti: "ISTJ",
		group: "TREASURE",
		agency: "YG",
		groupLogo: "/images/YG.png",
		instagram: "https://www.instagram.com/yg_treasure_official/",
		fancam: "https://www.youtube.com/watch?v=-IN7-p7ElSw",
	},
	태산: {
		englishName: "TAESAN",
		birth: "2004",
		hometown: "부산",
		hobby: "축구",
		mbti: "INFP",
		group: "BOYNEXTDOOR",
		agency: "KOZ",
		groupLogo: "/images/KOZ.png",
		instagram: " https://www.instagram.com/official.boynextdoor/",
		fancam: "https://www.youtube.com/watch?v=bxxCbRKfjHs",
	},
	명재현: {
		englishName: "MYUNG JAEHYUN",
		birth: "2003",
		hometown: "서울",
		hobby: "게임",
		mbti: "ISFJ",
		group: "BOYNEXTDOOR",
		agency: "KOZ",
		groupLogo: "/images/KOZ.png",
		instagram: " https://www.instagram.com/official.boynextdoor/",
		fancam: "https://www.youtube.com/watch?v=PX05ht8so7s",
	},
};
